$schema: "https://github.com/yaml-validator/yaml-validator/draft-01"
id: "https://github.com/yaml-validator/yaml-validator/metadata-1.0.0"

definitions:
  tag:
    enum:
      - "!gt "
      - "!join "
      - "!lt "
      - "!nn"
      - "!not."
      - "!not.gt "
      - "!not.lt "
      - "!not.nn"
      - "!unordered"

  validator:
    anyOf:
      - type: object
      - type: string
      - type: number
      - type: null
      - type: boolean
      - type: array
        items:
          $ref: "#"
      - $ref: "#"
      - $ref: "#/definitions/tag"
      - $ref: "#/definitions/validator"

patternProperties:
  ^.*$:
    $ref: "#/definitions/validator"
